FROM squidfunk/mkdocs-material:9.5 AS build

WORKDIR /docs

# Install pinned docs dependencies.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy docs source and macros hook.
COPY mkdocs.yml .
COPY main.py .
COPY docs/ docs/

# Build-time overrides for site metadata and external links.
ARG QAAS_DOCS_SITE_URL
ARG QAAS_DOCS_REPO_NAME
ARG QAAS_DOCS_REPO_URL
ARG QAAS_DOCS_SOCIAL_GITHUB_URL
ARG QAAS_DOCS_LINK_DOCS_SITE
ARG QAAS_DOCS_LINK_REPOSITORY_DOCS
ARG QAAS_DOCS_LINK_REPOSITORY_RUNNER
ARG QAAS_DOCS_LINK_REPOSITORY_MOCKER
ARG QAAS_DOCS_LINK_REPOSITORY_MOCKER_COMMUNICATION_OBJECTS
ARG QAAS_DOCS_LINK_REPOSITORY_FRAMEWORK
ARG QAAS_DOCS_LINK_REPOSITORY_ASSERTIONS
ARG QAAS_DOCS_LINK_REPOSITORY_GENERATORS
ARG QAAS_DOCS_LINK_REPOSITORY_PROBES
ARG QAAS_DOCS_LINK_REPOSITORY_PROCESSORS
ARG QAAS_DOCS_LINK_REPOSITORY_RUNNER_TEMPLATE
ARG QAAS_DOCS_LINK_REPOSITORY_MOCKER_TEMPLATE
ARG QAAS_DOCS_LINK_REPOSITORY_RUNNER_QUICKSTART_CODE
ARG QAAS_DOCS_LINK_REPOSITORY_RUNNER_QUICKSTART_YAML
ARG QAAS_DOCS_LINK_REPOSITORY_MOCKER_QUICKSTART_CODE
ARG QAAS_DOCS_LINK_REPOSITORY_MOCKER_QUICKSTART_YAML
ARG QAAS_DOCS_LINK_ALLURE_INSTALLATION_GUIDE
ARG QAAS_DOCS_LINK_DOTNET_SDK
ARG QAAS_DOCS_LINK_QAAS_COMMUNITY
ARG QAAS_DOCS_LINK_NUGET_FEED
ARG QAAS_DOCS_LINK_ARTIFACTORY
ARG QAAS_DOCS_LINK_RUNNER_SCHEMA
ARG QAAS_DOCS_LINK_MOCKER_SCHEMA

ENV QAAS_DOCS_SITE_URL=${QAAS_DOCS_SITE_URL} \
    QAAS_DOCS_REPO_NAME=${QAAS_DOCS_REPO_NAME} \
    QAAS_DOCS_REPO_URL=${QAAS_DOCS_REPO_URL} \
    QAAS_DOCS_SOCIAL_GITHUB_URL=${QAAS_DOCS_SOCIAL_GITHUB_URL} \
    QAAS_DOCS_LINK_DOCS_SITE=${QAAS_DOCS_LINK_DOCS_SITE} \
    QAAS_DOCS_LINK_REPOSITORY_DOCS=${QAAS_DOCS_LINK_REPOSITORY_DOCS} \
    QAAS_DOCS_LINK_REPOSITORY_RUNNER=${QAAS_DOCS_LINK_REPOSITORY_RUNNER} \
    QAAS_DOCS_LINK_REPOSITORY_MOCKER=${QAAS_DOCS_LINK_REPOSITORY_MOCKER} \
    QAAS_DOCS_LINK_REPOSITORY_MOCKER_COMMUNICATION_OBJECTS=${QAAS_DOCS_LINK_REPOSITORY_MOCKER_COMMUNICATION_OBJECTS} \
    QAAS_DOCS_LINK_REPOSITORY_FRAMEWORK=${QAAS_DOCS_LINK_REPOSITORY_FRAMEWORK} \
    QAAS_DOCS_LINK_REPOSITORY_ASSERTIONS=${QAAS_DOCS_LINK_REPOSITORY_ASSERTIONS} \
    QAAS_DOCS_LINK_REPOSITORY_GENERATORS=${QAAS_DOCS_LINK_REPOSITORY_GENERATORS} \
    QAAS_DOCS_LINK_REPOSITORY_PROBES=${QAAS_DOCS_LINK_REPOSITORY_PROBES} \
    QAAS_DOCS_LINK_REPOSITORY_PROCESSORS=${QAAS_DOCS_LINK_REPOSITORY_PROCESSORS} \
    QAAS_DOCS_LINK_REPOSITORY_RUNNER_TEMPLATE=${QAAS_DOCS_LINK_REPOSITORY_RUNNER_TEMPLATE} \
    QAAS_DOCS_LINK_REPOSITORY_MOCKER_TEMPLATE=${QAAS_DOCS_LINK_REPOSITORY_MOCKER_TEMPLATE} \
    QAAS_DOCS_LINK_REPOSITORY_RUNNER_QUICKSTART_CODE=${QAAS_DOCS_LINK_REPOSITORY_RUNNER_QUICKSTART_CODE} \
    QAAS_DOCS_LINK_REPOSITORY_RUNNER_QUICKSTART_YAML=${QAAS_DOCS_LINK_REPOSITORY_RUNNER_QUICKSTART_YAML} \
    QAAS_DOCS_LINK_REPOSITORY_MOCKER_QUICKSTART_CODE=${QAAS_DOCS_LINK_REPOSITORY_MOCKER_QUICKSTART_CODE} \
    QAAS_DOCS_LINK_REPOSITORY_MOCKER_QUICKSTART_YAML=${QAAS_DOCS_LINK_REPOSITORY_MOCKER_QUICKSTART_YAML} \
    QAAS_DOCS_LINK_ALLURE_INSTALLATION_GUIDE=${QAAS_DOCS_LINK_ALLURE_INSTALLATION_GUIDE} \
    QAAS_DOCS_LINK_DOTNET_SDK=${QAAS_DOCS_LINK_DOTNET_SDK} \
    QAAS_DOCS_LINK_QAAS_COMMUNITY=${QAAS_DOCS_LINK_QAAS_COMMUNITY} \
    QAAS_DOCS_LINK_NUGET_FEED=${QAAS_DOCS_LINK_NUGET_FEED} \
    QAAS_DOCS_LINK_ARTIFACTORY=${QAAS_DOCS_LINK_ARTIFACTORY} \
    QAAS_DOCS_LINK_RUNNER_SCHEMA=${QAAS_DOCS_LINK_RUNNER_SCHEMA} \
    QAAS_DOCS_LINK_MOCKER_SCHEMA=${QAAS_DOCS_LINK_MOCKER_SCHEMA}

RUN mkdocs build --clean

FROM python:3.11-alpine AS runtime

WORKDIR /site

COPY --from=build /docs/site /site

EXPOSE 8000

CMD ["sh", "-c", "python -m http.server \"${PORT:-8000}\" --bind 0.0.0.0 --directory /site"]
