# Build stage
FROM squidfunk/mkdocs-material:9.5 AS builder

WORKDIR /docs

# Install additional dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy documentation source
COPY mkdocs.yml .
COPY main.py .
COPY docs/ docs/

# Build-time overrides for dynamic links (optional)
ARG QAAS_DOCS_LINK_REPOSITORY_ORG
ARG QAAS_DOCS_LINK_REPOSITORY_DOCS
ARG QAAS_DOCS_LINK_REPOSITORY_RUNNER
ARG QAAS_DOCS_LINK_REPOSITORY_MOCKER
ARG QAAS_DOCS_LINK_REPOSITORY_FRAMEWORK
ARG QAAS_DOCS_LINK_REPOSITORY_ASSERTIONS
ARG QAAS_DOCS_LINK_REPOSITORY_GENERATORS
ARG QAAS_DOCS_LINK_REPOSITORY_PROBES
ARG QAAS_DOCS_LINK_REPOSITORY_PROCESSORS
ARG QAAS_DOCS_LINK_ALLURE_DOCS
ARG QAAS_DOCS_LINK_ALLURE_INSTALL
ARG QAAS_DOCS_LINK_DOTNET_SDK
ARG QAAS_DOCS_LINK_VSCODE_YAML_EXTENSION
ARG QAAS_DOCS_LINK_AUTOFAC
ARG QAAS_DOCS_LINK_QAAS_COMMUNITY
ARG QAAS_DOCS_LINK_NUGET_FEED_A
ARG QAAS_DOCS_LINK_NUGET_FEED_B
ARG QAAS_DOCS_LINK_NUGET_FEED_C
ARG QAAS_DOCS_LINK_QAAS_PROJECT_TEMPLATES
ARG QAAS_DOCS_LINK_DUMMYAPP_TESTS
ARG QAAS_DOCS_LINK_DUMMYAPP_HELM_CHART
ARG QAAS_DOCS_LINK_ARTIFACTORY
ARG QAAS_DOCS_LINK_REPOSITORY_MODULES
ARG QAAS_DOCS_LINK_REPOSITORY_VAP
ARG QAAS_DOCS_LINK_RUNNER_SCHEMA
ARG QAAS_DOCS_LINK_MOCKER_SCHEMA

# Propagate ARGs to ENV so the macros hook can read them
ENV QAAS_DOCS_LINK_REPOSITORY_ORG=${QAAS_DOCS_LINK_REPOSITORY_ORG} \
    QAAS_DOCS_LINK_REPOSITORY_DOCS=${QAAS_DOCS_LINK_REPOSITORY_DOCS} \
    QAAS_DOCS_LINK_REPOSITORY_RUNNER=${QAAS_DOCS_LINK_REPOSITORY_RUNNER} \
    QAAS_DOCS_LINK_REPOSITORY_MOCKER=${QAAS_DOCS_LINK_REPOSITORY_MOCKER} \
    QAAS_DOCS_LINK_REPOSITORY_FRAMEWORK=${QAAS_DOCS_LINK_REPOSITORY_FRAMEWORK} \
    QAAS_DOCS_LINK_REPOSITORY_ASSERTIONS=${QAAS_DOCS_LINK_REPOSITORY_ASSERTIONS} \
    QAAS_DOCS_LINK_REPOSITORY_GENERATORS=${QAAS_DOCS_LINK_REPOSITORY_GENERATORS} \
    QAAS_DOCS_LINK_REPOSITORY_PROBES=${QAAS_DOCS_LINK_REPOSITORY_PROBES} \
    QAAS_DOCS_LINK_REPOSITORY_PROCESSORS=${QAAS_DOCS_LINK_REPOSITORY_PROCESSORS} \
    QAAS_DOCS_LINK_ALLURE_DOCS=${QAAS_DOCS_LINK_ALLURE_DOCS} \
    QAAS_DOCS_LINK_ALLURE_INSTALL=${QAAS_DOCS_LINK_ALLURE_INSTALL} \
    QAAS_DOCS_LINK_DOTNET_SDK=${QAAS_DOCS_LINK_DOTNET_SDK} \
    QAAS_DOCS_LINK_VSCODE_YAML_EXTENSION=${QAAS_DOCS_LINK_VSCODE_YAML_EXTENSION} \
    QAAS_DOCS_LINK_AUTOFAC=${QAAS_DOCS_LINK_AUTOFAC} \
    QAAS_DOCS_LINK_QAAS_COMMUNITY=${QAAS_DOCS_LINK_QAAS_COMMUNITY} \
    QAAS_DOCS_LINK_NUGET_FEED_A=${QAAS_DOCS_LINK_NUGET_FEED_A} \
    QAAS_DOCS_LINK_NUGET_FEED_B=${QAAS_DOCS_LINK_NUGET_FEED_B} \
    QAAS_DOCS_LINK_NUGET_FEED_C=${QAAS_DOCS_LINK_NUGET_FEED_C} \
    QAAS_DOCS_LINK_QAAS_PROJECT_TEMPLATES=${QAAS_DOCS_LINK_QAAS_PROJECT_TEMPLATES} \
    QAAS_DOCS_LINK_DUMMYAPP_TESTS=${QAAS_DOCS_LINK_DUMMYAPP_TESTS} \
    QAAS_DOCS_LINK_DUMMYAPP_HELM_CHART=${QAAS_DOCS_LINK_DUMMYAPP_HELM_CHART} \
    QAAS_DOCS_LINK_ARTIFACTORY=${QAAS_DOCS_LINK_ARTIFACTORY} \
    QAAS_DOCS_LINK_REPOSITORY_MODULES=${QAAS_DOCS_LINK_REPOSITORY_MODULES} \
    QAAS_DOCS_LINK_REPOSITORY_VAP=${QAAS_DOCS_LINK_REPOSITORY_VAP} \
    QAAS_DOCS_LINK_RUNNER_SCHEMA=${QAAS_DOCS_LINK_RUNNER_SCHEMA} \
    QAAS_DOCS_LINK_MOCKER_SCHEMA=${QAAS_DOCS_LINK_MOCKER_SCHEMA}

# Build static site
RUN mkdocs build

# Production stage - lightweight nginx server
FROM nginx:alpine

# Copy built site to nginx
COPY --from=builder /docs/site /usr/share/nginx/html

# Expose port
EXPOSE 80

# nginx runs by default
