# Build stage
FROM squidfunk/mkdocs-material:9.5 AS builder

WORKDIR /docs

# Install additional dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy documentation source
COPY mkdocs.yml .
COPY main.py .
COPY docs/ docs/

# Build-time overrides for dynamic links (optional)
ARG QAAS_DOCS_LINK_GITHUB_ORG
ARG QAAS_DOCS_LINK_GITHUB_DOCS
ARG QAAS_DOCS_LINK_GITHUB_RUNNER
ARG QAAS_DOCS_LINK_GITHUB_MOCKER
ARG QAAS_DOCS_LINK_GITHUB_FRAMEWORK
ARG QAAS_DOCS_LINK_GITHUB_ASSERTIONS
ARG QAAS_DOCS_LINK_GITHUB_GENERATORS
ARG QAAS_DOCS_LINK_ALLURE_DOCS
ARG QAAS_DOCS_LINK_ALLURE_INSTALL
ARG QAAS_DOCS_LINK_DOTNET_SDK
ARG QAAS_DOCS_LINK_VSCODE_YAML_EXTENSION
ARG QAAS_DOCS_LINK_AUTOFAC

# Propagate ARGs to ENV so the macros hook can read them
ENV QAAS_DOCS_LINK_GITHUB_ORG=${QAAS_DOCS_LINK_GITHUB_ORG} \
    QAAS_DOCS_LINK_GITHUB_DOCS=${QAAS_DOCS_LINK_GITHUB_DOCS} \
    QAAS_DOCS_LINK_GITHUB_RUNNER=${QAAS_DOCS_LINK_GITHUB_RUNNER} \
    QAAS_DOCS_LINK_GITHUB_MOCKER=${QAAS_DOCS_LINK_GITHUB_MOCKER} \
    QAAS_DOCS_LINK_GITHUB_FRAMEWORK=${QAAS_DOCS_LINK_GITHUB_FRAMEWORK} \
    QAAS_DOCS_LINK_GITHUB_ASSERTIONS=${QAAS_DOCS_LINK_GITHUB_ASSERTIONS} \
    QAAS_DOCS_LINK_GITHUB_GENERATORS=${QAAS_DOCS_LINK_GITHUB_GENERATORS} \
    QAAS_DOCS_LINK_ALLURE_DOCS=${QAAS_DOCS_LINK_ALLURE_DOCS} \
    QAAS_DOCS_LINK_ALLURE_INSTALL=${QAAS_DOCS_LINK_ALLURE_INSTALL} \
    QAAS_DOCS_LINK_DOTNET_SDK=${QAAS_DOCS_LINK_DOTNET_SDK} \
    QAAS_DOCS_LINK_VSCODE_YAML_EXTENSION=${QAAS_DOCS_LINK_VSCODE_YAML_EXTENSION} \
    QAAS_DOCS_LINK_AUTOFAC=${QAAS_DOCS_LINK_AUTOFAC}

# Build static site
RUN mkdocs build

# Production stage - lightweight nginx server
FROM nginx:alpine

# Copy built site to nginx
COPY --from=builder /docs/site /usr/share/nginx/html

# Expose port
EXPOSE 80

# nginx runs by default
