site_name: QaaS Mocker CommunicationObjects Docs
repo_name: QaaS.Mocker.CommunicationObjects
repo_url: https://github.com/TheSmokeTeam/Qaas.Mocker.CommunicationObjects
docs_dir: docs

nav:
  - Guide: index.md
  - Reference: reference.md

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - toc:
      permalink: true
