site_name: QaaS Common Assertions Docs
repo_name: QaaS.Common.Assertions
repo_url: https://github.com/TheSmokeTeam/QaaS.Common.Assertions
docs_dir: docs
exclude_docs: |
  availableAssertions/*

nav:
  - Guide: index.md
  - Reference: reference.md

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - mike

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - toc:
      permalink: true
