site_name: QaaS Common Assertions Docs
docs_dir: docs/ 

nav:
  - Introduction: index.md
  - Available Assertions:
      - HermeticByExpectedOutputCount:
        - Overview: availableAssertions/HermeticByExpectedOutputCount/overview.md
        - Configurations: 
          - Table View: availableAssertions/HermeticByExpectedOutputCount/configuration/tableView.md 
          - Yaml View: availableAssertions/HermeticByExpectedOutputCount/configuration/yamlView.md 
      - HermeticByExpectedOutputCountInRange:
        - Overview: availableAssertions/HermeticByExpectedOutputCountInRange/overview.md
        - Configurations: 
          - Table View: availableAssertions/HermeticByExpectedOutputCountInRange/configuration/tableView.md 
          - Yaml View: availableAssertions/HermeticByExpectedOutputCountInRange/configuration/yamlView.md 
      - HermeticByInputOutputPercentage:
        - Overview: availableAssertions/HermeticByInputOutputPercentage/overview.md
        - Configurations: 
          - Table View: availableAssertions/HermeticByInputOutputPercentage/configuration/tableView.md 
          - Yaml View: availableAssertions/HermeticByInputOutputPercentage/configuration/yamlView.md 
      - HermeticByInputOutputPercentageInRange:
        - Overview: availableAssertions/HermeticByInputOutputPercentageInRange/overview.md
        - Configurations: 
          - Table View: availableAssertions/HermeticByInputOutputPercentageInRange/configuration/tableView.md 
          - Yaml View: availableAssertions/HermeticByInputOutputPercentageInRange/configuration/yamlView.md 
      - DelayByAverage:
        - Overview: availableAssertions/DelayByAverage/overview.md
        - Configurations: 
          - Table View: availableAssertions/DelayByAverage/configuration/tableView.md 
          - Yaml View: availableAssertions/DelayByAverage/configuration/yamlView.md 
      - DelayByChunks:
        - Overview: availableAssertions/DelayByChunks/overview.md
        - Configurations: 
          - Table View: availableAssertions/DelayByChunks/configuration/tableView.md 
          - Yaml View: availableAssertions/DelayByChunks/configuration/yamlView.md 
      - HttpStatus:
        - Overview: availableAssertions/HttpStatus/overview.md
        - Configurations: 
          - Table View: availableAssertions/HttpStatus/configuration/tableView.md 
          - Yaml View: availableAssertions/HttpStatus/configuration/yamlView.md 
      - OutputDeserializableTo:
        - Overview: availableAssertions/OutputDeserializableTo/overview.md
        - Configurations: 
          - Table View: availableAssertions/OutputDeserializableTo/configuration/tableView.md 
          - Yaml View: availableAssertions/OutputDeserializableTo/configuration/yamlView.md 
      - ObjectOutputJsonSchema:
        - Overview: availableAssertions/ObjectOutputJsonSchema/overview.md
        - Configurations: 
          - Table View: availableAssertions/ObjectOutputJsonSchema/configuration/tableView.md 
          - Yaml View: availableAssertions/ObjectOutputJsonSchema/configuration/yamlView.md 
      - OutputContentByExpectedCsvResults:
        - Overview: availableAssertions/OutputContentByExpectedCsvResults/overview.md
        - Configurations: 
          - Table View: availableAssertions/OutputContentByExpectedCsvResults/configuration/tableView.md 
          - Yaml View: availableAssertions/OutputContentByExpectedCsvResults/configuration/yamlView.md 
      - ValidateHermeticMetricsByInputOutputPercentage:
        - Overview: availableAssertions/ValidateHermeticMetricsByInputOutputPercentage/overview.md
        - Configurations: 
          - Table View: availableAssertions/ValidateHermeticMetricsByInputOutputPercentage/configuration/tableView.md 
          - Yaml View: availableAssertions/ValidateHermeticMetricsByInputOutputPercentage/configuration/yamlView.md 
theme:
  name: readthedocs

plugins:
  - search

markdown_extensions:
  - fenced_code
  - tables
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
