site_name: QaaS Common Processors Docs
docs_dir: docs/

nav:
  - Introduction: index.md
  - Available Processors:
      - ExampleProcessor: availableProcessors/exampleProcessor.md
      - DummyTransactionProcessor: availableProcessors/dummyTransactionProcessor.md
      - GrpcEchoProcessor: availableProcessors/grpcEchoProcessor.md
      - StatusCodeTransactionProcessor: availableProcessors/statusCodeTransactionProcessor.md

theme:
  name: readthedocs

plugins:
  - search

markdown_extensions:
  - fenced_code
  - tables
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
