site_name: QaaS Common Generators Docs
docs_dir: docs/ 

nav:
  - Introduction: index.md
  - Available Generators:
      - FromFileSystem:
        - Overview: availableGenerators/FromFileSystem/overview.md
        - Configurations: 
          - Table View: availableGenerators/FromFileSystem/configuration/tableView.md 
          - Yaml View: availableGenerators/FromFileSystem/configuration/yamlView.md 
      - FromS3:
        - Overview: availableGenerators/FromS3/overview.md
        - Configurations: 
          - Table View: availableGenerators/FromS3/configuration/tableView.md 
          - Yaml View: availableGenerators/FromS3/configuration/yamlView.md 
      - FromDataLake:
        - Overview: availableGenerators/FromDataLake/overview.md
        - Configurations: 
          - Table View: availableGenerators/FromDataLake/configuration/tableView.md 
          - Yaml View: availableGenerators/FromDataLake/configuration/yamlView.md 
      - FromDataSources:
        - Overview: availableGenerators/FromDataSources/overview.md
        - Configurations: 
          - Table View: availableGenerators/FromDataSources/configuration/tableView.md 
          - Yaml View: availableGenerators/FromDataSources/configuration/yamlView.md 
      - FromLettuceDataSources:
        - Overview: availableGenerators/FromLettuceDataSources/overview.md
        - Configurations: 
          - Table View: availableGenerators/FromLettuceDataSources/configuration/tableView.md 
          - Yaml View: availableGenerators/FromLettuceDataSources/configuration/yamlView.md 
      - FromSessionDataDataSources:
        - Overview: availableGenerators/FromSessionDataDataSources/overview.md
        - Configurations: 
          - Table View: availableGenerators/FromSessionDataDataSources/configuration/tableView.md 
          - Yaml View: availableGenerators/FromSessionDataDataSources/configuration/yamlView.md 
      - Json:
        - Overview: availableGenerators/Json/overview.md
        - Configurations: 
          - Table View: availableGenerators/Json/configuration/tableView.md 
          - Yaml View: availableGenerators/Json/configuration/yamlView.md 
      - JsonSchemaDraft4:
        - Overview: availableGenerators/JsonSchemaDraft4/overview.md
        - Configurations: 
          - Table View: availableGenerators/JsonSchemaDraft4/configuration/tableView.md 
          - Yaml View: availableGenerators/JsonSchemaDraft4/configuration/yamlView.md 
      - LettuceFromFileSystem:
        - Overview: availableGenerators/LettuceFromFileSystem/overview.md
        - Configurations: 
          - Table View: availableGenerators/LettuceFromFileSystem/configuration/tableView.md 
          - Yaml View: availableGenerators/LettuceFromFileSystem/configuration/yamlView.md 
      - Stacking:
        - Overview: availableGenerators/Stacking/overview.md
        - Configurations: 
          - Table View: availableGenerators/Stacking/configuration/tableView.md 
          - Yaml View: availableGenerators/Stacking/configuration/yamlView.md 
theme:
  name: readthedocs

plugins:
  - search

markdown_extensions:
  - fenced_code
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

