site_name: QaaS Common Generators Docs
repo_name: QaaS.Common.Generators
repo_url: https://github.com/TheSmokeTeam/QaaS.Common.Generators
docs_dir: docs
exclude_docs: |
  availableGenerators/*

nav:
  - Guide: index.md
  - Reference: reference.md

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - mike

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - toc:
      permalink: true

