site_name: QaaS Framework Docs
repo_name: QaaS Framework
repo_url: "REDA/qaas.framework.git"
docs_dir: docs/ 

nav:
  - Introduction: index.md
  - Projects:
    - SDK: projects/sdk.md
    - Configuration: projects/configuration.md
    - Executions: projects/executions.md
    - Infrastructure: projects/infrastructure.md
    - Policies: projects/policies.md
    - Protocols: projects/protocols.md
    - Providers: projects/providers.md
    - Serialization: projects/serialization.md
  - QaaS Docs: REDA/v4/
theme:
  name: material
  highlights: false
  font: false
  features:
    - content.code.annotate
    - navigation.tabs

  palette:
    - scheme: slate
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  include_search_page: false
  search_index_only: true

  icon:
    repo: fontawesome/brands/gitlab
  logo: assets/qaas-logo.png
  favicon: assets/qaas-logo.png

extra_css:
  - assets/chat-widget.js

extra_javascript:
  - assets/chat-widget.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
