site_name: QaaS Mocker Docs
docs_dir: docs/ 

nav:
  - Introduction: index.md
  - Quick Start:
    - Installation: quickStart/installation.md
    - Create Mock: quickStart/createMock.md
    - Deploy Mock: quickStart/deployMock.md
    - Integrate with Tests: quickStart/integrateWithTests.md
  - User Interfaces:
    - Mocker:
      - Configuration Sections:
        - userInterfaces/mocker/configurationSections/configurationSections.md
        - DataSources: 
            - Overview: userInterfaces/mocker/configurationSections/dataSources/overview.md
            - Configurations: 
                - Table View: userInterfaces/mocker/configurationSections/dataSources/configurations/tableView.md 
                - Yaml View: userInterfaces/mocker/configurationSections/dataSources/configurations/yamlView.md
        - Stubs: 
            - Overview: userInterfaces/mocker/configurationSections/stubs/overview.md
            # - QaaS.Common.Processors: REDA
            - Configurations: 
                - Table View: userInterfaces/mocker/configurationSections/stubs/configurations/tableView.md 
                - Yaml View: userInterfaces/mocker/configurationSections/stubs/configurations/yamlView.md  
        - Controller: 
            - Overview: userInterfaces/mocker/configurationSections/controller/overview.md
            - Configurations: 
                - Table View: userInterfaces/mocker/configurationSections/controller/configurations/tableView.md 
                - Yaml View: userInterfaces/mocker/configurationSections/controller/configurations/yamlView.md  
        - Server: 
            - Overview: userInterfaces/mocker/configurationSections/server/overview.md
            - Configurations: 
                - Table View: userInterfaces/mocker/configurationSections/server/configurations/tableView.md 
                - Yaml View: userInterfaces/mocker/configurationSections/server/configurations/yamlView.md 

theme:
  name: readthedocs

markdown_extensions:
  - fenced_code
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
plugins:
  - search
