site_name: QaaS Mocker Docs
repo_name: QaaS.Mocker
repo_url: "REDA/qaas-mocker-docs.git"
docs_dir: docs/ 

nav:
  - Introduction: index.md
  - Quick Start:
    - Installation: quickStart/installation.md
    - Create Mock: quickStart/createMock.md
    - Deploy Mock: quickStart/deployMock.md
    - Integrate with Tests: quickStart/integrateWithTests.md
  - User Interfaces:
    - Mocker:
      - Configuration Sections:
        - userInterfaces/mocker/configurationSections/configurationSections.md
        - DataSources: 
            - Overview: userInterfaces/mocker/configurationSections/dataSources/overview.md
            - QaaS.Common.Generators: REDA
            - Configurations: 
                - Table View: userInterfaces/mocker/configurationSections/dataSources/configurations/tableView.md 
                - Yaml View: userInterfaces/mocker/configurationSections/dataSources/configurations/yamlView.md
        - Stubs: 
            - Overview: userInterfaces/mocker/configurationSections/stubs/overview.md
            # - QaaS.Common.Processors: REDA
            - Configurations: 
                - Table View: userInterfaces/mocker/configurationSections/stubs/configurations/tableView.md 
                - Yaml View: userInterfaces/mocker/configurationSections/stubs/configurations/yamlView.md  
        - Controller: 
            - Overview: userInterfaces/mocker/configurationSections/controller/overview.md
            - Configurations: 
                - Table View: userInterfaces/mocker/configurationSections/controller/configurations/tableView.md 
                - Yaml View: userInterfaces/mocker/configurationSections/controller/configurations/yamlView.md  
        - Server: 
            - Overview: userInterfaces/mocker/configurationSections/server/overview.md
            - Configurations: 
                - Table View: userInterfaces/mocker/configurationSections/server/configurations/tableView.md 
                - Yaml View: userInterfaces/mocker/configurationSections/server/configurations/yamlView.md 
  - QaaS: REDA

theme:
  name: material
  highlightjs: false
  font: false
  features:
    - content.code.annotate
    - navigation.tabs

  palette:
    - scheme: slate
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  include_search_page: false
  search_index_only: true

  icon:
    repo: fontawesome/brands/gitlab
  logo: assets/qaas-mocker-logo.png
  favicon: assets/qaas-mocker-logo.png

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
