# lychee link-checker config
exclude = [
  "^https?://localhost",
  "^https?://127\\.",
  "^https?://TheSmokeTeam.github.io/qaas-docs",  # self
]
exclude_path = ["site/_meta", "site/_generated"]
accept = [200, 201, 202, 203, 204, 206, 301, 302, 303, 307, 308, 403, 429]
max_concurrency = 8
max_redirects = 5
timeout = 15
no_progress = true
cache = true
max_cache_age = "1d"
